### ISSUE TITLE
Buffer seems to miss volume and url options

### ISSUE THREAD

**Issue by carstenheisterkamp** [Tonejs/TypeScript#19]
When I try to initialize a synth or any player with options I get the following errors. 

`     let player = new Tone.Player({
        "url": "./path/to/sample.mp3"",
        "callback": function() {}, 
        "playbackRate"  : 1,
        "autostart": false,
        "loop": true,
        "fadeIn":1.0,
        "fadeOut":1.0
      }).toMaster()`

 Object literal may only specify known properties, and '"url"' does not exist in type 'Buffer'.

`let synth = new Tone.MonoSynth({
        "volume" : -6,
        "oscillator" : {
          "type" : "square"
      },
      "envelope" : {
        "attack" : 0.1
      }
      }).toMaster()`

Object literal may only specify known properties, and '"volume"' does not exist in type 'MonoSynthOptions'.

**Comment by panmichal** [comment]
Notice that both `url` and `volume` properties are first properties of given objects. So it's not about those specific ones, constructors of the`Player` class does not expect to receive such object. It's either `string` or `AudioBuffer` for url.
Looks like types in this repo are out of sync - probably this branch is up to date https://github.com/Tonejs/Tone.js/tree/typescript ?
