### ISSUE TITLE
Maybe it's worth to consider dts-gen as starting point

### ISSUE THREAD

**Issue by cansik** [Tonejs/TypeScript#7]
It seems that Typescript definition currently is a handwritten file. Wouldn't it be better to start of with a [dts-gen](https://github.com/Microsoft/dts-gen) generated file and add the types to it? So it is a valid definition (with all classes / methods included), but at the beginning just with the any type.

I tried to convert it in the browser, but dts-gen crashes because of following message:

```js
Tone.min.js:12 Uncaught TypeError: Cannot read property 'type' of undefined
    at t.Oscillator.get (Tone.min.js:12)
    at browser-bundle.js:1
    at Array.map (<anonymous>)
    at p (browser-bundle.js:1)
    at n (browser-bundle.js:1)
    at l (browser-bundle.js:1)
    at n (browser-bundle.js:1)
    at l (browser-bundle.js:1)
    at Object.s [as generateIdentifierDeclarationFile] (browser-bundle.js:1)
    at HTMLInputElement.<anonymous> (browser-bundle.js:1)
```

Maybe someone could try to convert it with the shell commands.

**Comment by Engid** [comment]
Using an automated tool is a great idea. The Tone source code looks like it has very thorough JSDoc style annotations, so maybe that could be used to generate a .d.ts file. There are tools like angulars [clutz](https://github.com/angular/clutz) that can convert Closure to `.d.ts` Typescript definitions. I tried to get clutz up and running tonight but it has some issues running on Windows 10. I might try again in the Windows Subsystem for Linux tomorrow, but if anyone else wants to give it a shot it might be interesting.

**Comment by mark-atk** [comment]
Would also be great if there was a way to easily identify what parts of the Tone.js library wasn't typed here yet. Would lower the overhead to contributing.

**Comment by jcapinc** [comment]
The current typings make the library pretty usable as a typescript library, so im not sure this is necessary at this point, should we close this issue?

**Comment by tambien** [comment]
Thanks @jcapinc. Old issue, going to close
